### PR TITLE
Allow EZPaS to work on 1.16.3

### PR DESCRIPTION
**Pull request by YTG1234**
1.16.3 didn't have any important changes

### CODE REVIEW

**Comment by YTG1234** [comment]
@cakewhip

**Comment by YTG1234** [comment]
This is very important to me, so I'm mentioning you (very sorry) @cakewhip

**Comment by cakewhip** [comment]
I'll do some version bumping real quick and a release will come out soon. Thanks!

**Comment by YTG1234** [comment]
Wow, that was quick

**Pull request merged**
